
LOG_STDOUT = True

AUTHOR_AFFILIATION_SOLRQUERY_URL = "http://api.adsabs.harvard.edu/v1/search/bigquery"
AUTHOR_AFFILIATION_SERVICE_ADSWS_API_TOKEN = 'this is a secret api token!'

AUTHOR_AFFILATION_SERVICE_MAX_RECORDS_SOLR = 1000
